In [ ]:
#1 Create a NumPy array and make a copy of it. Modify the original array and print both the original and copied arrays.

import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
a[4]=19
print(a)
print(b)

[ 1  2  3  4 19]
[1 2 3 4 5]


In [ ]:
#2  Create a view of a NumPy array. Modify the view and print both the original and theview. How do the results compare to using a copy?

import numpy as np
a=np.array([1,2,3,4,5])
print(a)
b=a.view()
print(b)
b[4]=7
print(b)
print("a=",a)
print(b.base)

[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 7]
a= [1 2 3 4 7]
[1 2 3 4 7]


In [ ]:
#3  Explain the difference between array.copy() and array.view() in NumPy. Provide anexample to illustrate the difference.


import numpy as np
a=np.array([1,2,3,4,5])
b=a.copy()
c=a.view()
print(b.base)
print(c.base)

None
[1 2 3 4 5]


In [ ]:
#4  Create a 2D NumPy array and generate a view that represents only the first row.Modify this view and print the changes in both the original array and the view.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a[0].view()
print(b)
a[0,1]=9
print(a)
print("b =",b)


[1 2 3]
[[1 9 3]
 [4 5 6]]
b = [1 9 3]


In [ ]:
#5 Create a NumPy array and another array by slicing the first array. Check whether the second array is a copy or a view of the first array.


import numpy as np
a=np.array([1,2,3,4,5,6,7])
b=np.array(a[1:5])
print(b)
print(b.base)

[2 3 4 5]
None


In [ ]:
#6 Use the np.may_share_memory() function to check if two arrays share the same memory. Provide an example.

import numpy as np
a=np.array([1,2,3,4])
b=np.array([5,6,7,8,9])
c=np.may_share_memory(a,b)   # may_share_memory returns False as they share memory
print(c)

False


In [ ]:
#7 Create a NumPy array, then use the reshape() function on it. Check whether the reshaped array is a view or a copy.

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b.base)

[1 2 3 4 5 6 7 8 9]


In [ ]:
#8 Create a NumPy array, then use the reshape() function on it. Check whether the reshaped array is a view or a copy.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
print("shape of a :",a.shape)
b=a.reshape(3,2)
print(b)
print("shape of b :",b.shape)

shape of a : (2, 3)
[[1 2]
 [3 4]
 [5 6]]
shape of b : (3, 2)


In [ ]:
#9 Given a 1D array of length 12, reshape it into a 2D array with 3 rows. Then, reshape it into a 3D array. Print the shapes at each step.

import numpy as np
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("a = ",a)
b=a.reshape(2,3,2)
print("b = ",b)
c=a.reshape(3,2,2)
print("c = ",c)

a =  [ 1  2  3  4  5  6  7  8  9 10 11 12]
b =  [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
c =  [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
import numpy as np
a=np.arange(12)
print("a = ",a)
b=a.reshape(2,3,2)
print("b = ",b)
c=a.reshape(3,2,2)
print("c = ",c)

a =  [ 0  1  2  3  4  5  6  7  8  9 10 11]
b =  [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]
c =  [[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [ ]:
#10 Create a 3x4 matrix and then reshape it into a 2x6 matrix. Verify if reshaping changes the data content.

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b=a.reshape(2,6)
print(b)
print(b.dtype)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
int64


In [ ]:
#11 Reshape a 2D array into a 3D array. Then reshape it back to its original 2D shape.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
b=a.reshape(3,1,2)
print(b)
print("-------------------------------")
c=b.reshape(2,3)
print(c)

[[[1 2]]

 [[3 4]]

 [[5 6]]]
-------------------------------
[[1 2 3]
 [4 5 6]]


In [ ]:
#12 Given a 4x4 matrix, reshape it into a 2D array with dimensions 2x8. Then, reshape it back to 4x4.

import numpy as np
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print("a = ",a)
b=a.reshape(2,8)
print("b = ",b)
c=b.reshape(4,4)
print("c = ",c)

a =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
b =  [[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]
c =  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [ ]:
#13 Create a 3D array and flatten it into a 1D array using reshape(-1).

import numpy as np
a=np.array([[[1,2,3]],[[4,5,6]]])
b=a.reshape(-1)
print(b)

[1 2 3 4 5 6]


In [ ]:
#14 Create a 3x3 matrix and iterate over its elements row by row.

import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
for x in a:
  print(x)

[1 2 3]
[4 5 6]
[7 8 9]


In [ ]:
#15 Create a 2D array. Print index of each element including that element.

a=np.array([[1,2,3],[4,5,6]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6


In [ ]:
#16 Iterate over a 3D array and print each element, along with its corresponding index.

import numpy as np
a=np.array([[[1,2,3]],[[4,5,6]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 0, 2) 6


In [ ]:
#17 Create a 2D NumPy array and use np.nditer() to iterate over it. Print each element.

a=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(a):
  print(x)

1
2
3
4
5
6


In [ ]:
#18 Create a 3D array. Print each element and its corresponding index.

import numpy as np
a=np.array([[[1,2,3]],[[4,5,6]]])
for idx,x in np.ndenumerate(a):
  print(idx,x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(1, 0, 0) 4
(1, 0, 1) 5
(1, 0, 2) 6


In [ ]:
#19 Create a 6D array and use nditer() and print each element .


import numpy as np
a=np.array(([1,2,3,4,5,6]),ndmin=6)
print(a)
for x in np.nditer(a):
  print(x)

[[[[[[1 2 3 4 5 6]]]]]]
1
2
3
4
5
6


In [ ]:
#20 Create a 2D integer array and use nditer() to iterate over it as if it were an float array. Print the elements.

import numpy as np
a=np.array([[1,2,3],[4,5,6]])
for x in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(x)

1.0
2.0
3.0
4.0
5.0
6.0


In [ ]:
#21 Use nditer() to iterate over a mixed data type array, where some elements are floats and others are integers.


import numpy as np
a=np.array([1,2.3,4,5.6])
for x in np.nditer(a):
  print(x)

1.0
2.3
4.0
5.6


In [ ]:
#22 Create a 2D array and iterate over it using nditer() with op_dtypes set to different types. Observe and explain the results.

import numpy as np
a=np.array([1,2,3,4,5])
for x in np.nditer(a,flags=['buffered'],op_dtypes=[float]):
  print(x)

1.0
2.0
3.0
4.0
5.0


In [1]:
#23 Create a 1D array of 10 elements and iterate over it using a step size of 2. Print the accessed elements.


import numpy as np
a=np.arange(10)
for x in a[::2]:
  print(x)


0
2
4
6
8


In [5]:
#24 Iterate over every second element of a 2D array along with indices of the elements

import numpy as np
a=np.arange(9).reshape(3,3)
print(a)
for idx,x in np.ndenumerate(a[::2]):
  print(idx,x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 6
(1, 1) 7
(1, 2) 8


In [8]:
#25.Create a 3D array and iterate over every second element. Print the elements accessed in each step along with indices of element.


import numpy as np
a=np.arange(9).reshape(3,3)
print(a)
b=a[::2]
for idx,x in np.ndenumerate(b):
  print(idx,x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 6
(1, 1) 7
(1, 2) 8
